--ATIVIDADE 

CREATE DATABASE escola;
USE	escola;
CREATE TABLE Alunos(
--IDENTITY VAI INCREMENTAR AUTOMATICAMENTE A KEY 
--ULTIMA LINHA DE COMANDO NAO PODE TER FIRGULA','
	id_equipe INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	nome VARCHAR(255) NOT NULL,
	idade INT NOT NULL
);

CREATE DATABASE bibilhoteca;
USE bibilhoteca;
CREATE TABLE Editora(
--IDENTITY VAI INCREMENTAR AUTOMATICAMENTE A KEY 
--ULTIMA LINHA DE COMANDO NAO PODE TER FIRGULA','
	id_editora INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	nome_Editora VARCHAR(255) NOT NULL,
	nome_endereco VARCHAR(255) NOT NULL,
	nome_telefone INT NOT NULL,
	data_defundacao DATE NOT NULL
);
CREATE TABLE Livros(
--IDENTITY VAI INCREMENTAR AUTOMATICAMENTE A KEY 
--ULTIMA LINHA DE COMANDO NAO PODE TER FIRGULA','
	id_livros INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	titulo_livro VARCHAR(255) NOT NULL,
	auto_livro VARCHAR(255) NOT NULL,
	categoria VARCHAR(255) NOT NULL,
	preco DECIMAL(2,2) NOT NULL,
	data_cadastro_livro DATE NOT NULL,
	disponibidade_livro BINARY NOT NULL,
	resumo_Livro VARCHAR(1000) NOT NULL,
	num_exemplares INT NOT NULL,
	id_editora INT NOT NULL,

	--Chaves Estrangeiras =>
	FOREIGN KEY (id_editora) REFERENCES Editora(id_editora)

);